version: '3'

services:
  app:
    container_name: discord-bot
    image: ghcr.io/shimima13/discord-bot-upload-cf:latest
    build: .
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      CLOUDFLARE_ZONE_ID: ${CLOUDFLARE_ZONE_ID}